/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ApacheSolr.Model;
using ApacheSolr.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ApacheSolr.Test.Model
{
    /// <summary>
    ///  Class for testing ReloadCoreRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReloadCoreRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReloadCoreRequestBodyModel
        //private ReloadCoreRequestBodyModel instance;

        public ReloadCoreRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of ReloadCoreRequestBodyModel
            //instance = new ReloadCoreRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReloadCoreRequestBodyModel
        /// </summary>
        [Fact]
        public void ReloadCoreRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReloadCoreRequestBodyModel
            //Assert.IsType<ReloadCoreRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
