/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = SolrClient.Client.FileParameter;
using OpenAPIDateConverter = SolrClient.Client.OpenAPIDateConverter;

namespace SolrClient.Model
{
    /// <summary>
    /// The collection of snapshots found for the requested core.
    /// </summary>
    [DataContract(Name = "SnapshotInformation")]
    public partial class SnapshotInformationModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SnapshotInformationModel" /> class.
        /// </summary>
        /// <param name="indexDirPath">The path to the directory containing the index files..</param>
        /// <param name="generationNumber">The generation value for the snapshot..</param>
        public SnapshotInformationModel(string indexDirPath = default(string), long generationNumber = default(long))
        {
            this.IndexDirPath = indexDirPath;
            this.GenerationNumber = generationNumber;
        }

        /// <summary>
        /// The path to the directory containing the index files.
        /// </summary>
        /// <value>The path to the directory containing the index files.</value>
        [DataMember(Name = "indexDirPath", EmitDefaultValue = false)]
        public string IndexDirPath { get; set; }

        /// <summary>
        /// The generation value for the snapshot.
        /// </summary>
        /// <value>The generation value for the snapshot.</value>
        [DataMember(Name = "generationNumber", EmitDefaultValue = false)]
        public long GenerationNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SnapshotInformationModel {\n");
            sb.Append("  IndexDirPath: ").Append(IndexDirPath).Append("\n");
            sb.Append("  GenerationNumber: ").Append(GenerationNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
