/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolrClient.Model;
using SolrClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolrClient.Test.Model
{
    /// <summary>
    ///  Class for testing BalanceShardUniqueRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceShardUniqueRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BalanceShardUniqueRequestBodyModel
        //private BalanceShardUniqueRequestBodyModel instance;

        public BalanceShardUniqueRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of BalanceShardUniqueRequestBodyModel
            //instance = new BalanceShardUniqueRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BalanceShardUniqueRequestBodyModel
        /// </summary>
        [Fact]
        public void BalanceShardUniqueRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" BalanceShardUniqueRequestBodyModel
            //Assert.IsType<BalanceShardUniqueRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Fact]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }

        /// <summary>
        /// Test the property 'OnlyActiveNodes'
        /// </summary>
        [Fact]
        public void OnlyActiveNodesTest()
        {
            // TODO unit test for the property 'OnlyActiveNodes'
        }

        /// <summary>
        /// Test the property 'ShardUnique'
        /// </summary>
        [Fact]
        public void ShardUniqueTest()
        {
            // TODO unit test for the property 'ShardUnique'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
