/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolrClient.Model;
using SolrClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolrClient.Test.Model
{
    /// <summary>
    ///  Class for testing IndexVersionResponseModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IndexVersionResponseModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IndexVersionResponseModel
        //private IndexVersionResponseModel instance;

        public IndexVersionResponseModelTests()
        {
            // TODO uncomment below to create an instance of IndexVersionResponseModel
            //instance = new IndexVersionResponseModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IndexVersionResponseModel
        /// </summary>
        [Fact]
        public void IndexVersionResponseModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" IndexVersionResponseModel
            //Assert.IsType<IndexVersionResponseModel>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Indexversion'
        /// </summary>
        [Fact]
        public void IndexversionTest()
        {
            // TODO unit test for the property 'Indexversion'
        }

        /// <summary>
        /// Test the property 'Generation'
        /// </summary>
        [Fact]
        public void GenerationTest()
        {
            // TODO unit test for the property 'Generation'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
