/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolrClient.Model;
using SolrClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolrClient.Test.Model
{
    /// <summary>
    ///  Class for testing ReplaceNodeRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplaceNodeRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplaceNodeRequestBodyModel
        //private ReplaceNodeRequestBodyModel instance;

        public ReplaceNodeRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of ReplaceNodeRequestBodyModel
            //instance = new ReplaceNodeRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplaceNodeRequestBodyModel
        /// </summary>
        [Fact]
        public void ReplaceNodeRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplaceNodeRequestBodyModel
            //Assert.IsType<ReplaceNodeRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'TargetNodeName'
        /// </summary>
        [Fact]
        public void TargetNodeNameTest()
        {
            // TODO unit test for the property 'TargetNodeName'
        }

        /// <summary>
        /// Test the property 'WaitForFinalState'
        /// </summary>
        [Fact]
        public void WaitForFinalStateTest()
        {
            // TODO unit test for the property 'WaitForFinalState'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
