/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SolrClient.Model;
using SolrClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SolrClient.Test.Model
{
    /// <summary>
    ///  Class for testing SwapCoresRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SwapCoresRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SwapCoresRequestBodyModel
        //private SwapCoresRequestBodyModel instance;

        public SwapCoresRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of SwapCoresRequestBodyModel
            //instance = new SwapCoresRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SwapCoresRequestBodyModel
        /// </summary>
        [Fact]
        public void SwapCoresRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SwapCoresRequestBodyModel
            //Assert.IsType<SwapCoresRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'With'
        /// </summary>
        [Fact]
        public void WithTest()
        {
            // TODO unit test for the property 'With'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
