/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing CollectionPropertiesApi
    /// </summary>
    public sealed class CollectionPropertiesApiTests : ApiTestsBase
    {
        private readonly ICollectionPropertiesApi _instance;

        public CollectionPropertiesApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ICollectionPropertiesApi>();
        }

        /// <summary>
        /// Test CreateOrUpdateCollectionProperty
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateOrUpdateCollectionPropertyAsyncTest()
        {
            string collName = default!;
            string propName = default!;
            Client.Option<UpdateCollectionPropertyRequestBody> updateCollectionPropertyRequestBody = default!;
            var response = await _instance.CreateOrUpdateCollectionPropertyAsync(collName, propName, updateCollectionPropertyRequestBody);
            var model = response.Default();
            Assert.IsType<SolrJerseyResponse>(model);
        }

        /// <summary>
        /// Test DeleteCollectionProperty
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteCollectionPropertyAsyncTest()
        {
            string collName = default!;
            string propName = default!;
            var response = await _instance.DeleteCollectionPropertyAsync(collName, propName);
            var model = response.Default();
            Assert.IsType<SolrJerseyResponse>(model);
        }
    }
}
