// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// LogMessagesResponse
    /// </summary>
    public partial class LogMessagesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LogMessagesResponse" /> class.
        /// </summary>
        /// <param name="info">info</param>
        /// <param name="responseHeader">responseHeader</param>
        /// <param name="error">error</param>
        /// <param name="watcher">watcher</param>
        /// <param name="history">history</param>
        [JsonConstructor]
        public LogMessagesResponse(Option<LogMessageInfo?> info = default, Option<ResponseHeader?> responseHeader = default, Option<ErrorInfo?> error = default, Option<string?> watcher = default, Option<Object?> history = default)
        {
            InfoOption = info;
            ResponseHeaderOption = responseHeader;
            ErrorOption = error;
            WatcherOption = watcher;
            HistoryOption = history;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Info
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LogMessageInfo?> InfoOption { get; private set; }

        /// <summary>
        /// Gets or Sets Info
        /// </summary>
        [JsonPropertyName("info")]
        public LogMessageInfo? Info { get { return this.InfoOption; } set { this.InfoOption = new(value); } }

        /// <summary>
        /// Used to track the state of ResponseHeader
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResponseHeader?> ResponseHeaderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResponseHeader
        /// </summary>
        [JsonPropertyName("responseHeader")]
        public ResponseHeader? ResponseHeader { get { return this.ResponseHeaderOption; } set { this.ResponseHeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ErrorInfo?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public ErrorInfo? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Watcher
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WatcherOption { get; private set; }

        /// <summary>
        /// Gets or Sets Watcher
        /// </summary>
        [JsonPropertyName("watcher")]
        public string? Watcher { get { return this.WatcherOption; } set { this.WatcherOption = new(value); } }

        /// <summary>
        /// Used to track the state of History
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> HistoryOption { get; private set; }

        /// <summary>
        /// Gets or Sets History
        /// </summary>
        [JsonPropertyName("history")]
        public Object? History { get { return this.HistoryOption; } set { this.HistoryOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LogMessagesResponse {\n");
            sb.Append("  Info: ").Append(Info).Append("\n");
            sb.Append("  ResponseHeader: ").Append(ResponseHeader).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Watcher: ").Append(Watcher).Append("\n");
            sb.Append("  History: ").Append(History).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LogMessagesResponse" />
    /// </summary>
    public class LogMessagesResponseJsonConverter : JsonConverter<LogMessagesResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="LogMessagesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LogMessagesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<LogMessageInfo?> info = default;
            Option<ResponseHeader?> responseHeader = default;
            Option<ErrorInfo?> error = default;
            Option<string?> watcher = default;
            Option<Object?> history = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "info":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                info = new Option<LogMessageInfo?>(JsonSerializer.Deserialize<LogMessageInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "responseHeader":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                responseHeader = new Option<ResponseHeader?>(JsonSerializer.Deserialize<ResponseHeader>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                error = new Option<ErrorInfo?>(JsonSerializer.Deserialize<ErrorInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "watcher":
                            watcher = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "history":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                history = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (info.IsSet && info.Value == null)
                throw new ArgumentNullException(nameof(info), "Property is not nullable for class LogMessagesResponse.");

            if (responseHeader.IsSet && responseHeader.Value == null)
                throw new ArgumentNullException(nameof(responseHeader), "Property is not nullable for class LogMessagesResponse.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class LogMessagesResponse.");

            if (watcher.IsSet && watcher.Value == null)
                throw new ArgumentNullException(nameof(watcher), "Property is not nullable for class LogMessagesResponse.");

            if (history.IsSet && history.Value == null)
                throw new ArgumentNullException(nameof(history), "Property is not nullable for class LogMessagesResponse.");

            return new LogMessagesResponse(info, responseHeader, error, watcher, history);
        }

        /// <summary>
        /// Serializes a <see cref="LogMessagesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logMessagesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LogMessagesResponse logMessagesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, logMessagesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="LogMessagesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="logMessagesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, LogMessagesResponse logMessagesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (logMessagesResponse.InfoOption.IsSet && logMessagesResponse.Info == null)
                throw new ArgumentNullException(nameof(logMessagesResponse.Info), "Property is required for class LogMessagesResponse.");

            if (logMessagesResponse.ResponseHeaderOption.IsSet && logMessagesResponse.ResponseHeader == null)
                throw new ArgumentNullException(nameof(logMessagesResponse.ResponseHeader), "Property is required for class LogMessagesResponse.");

            if (logMessagesResponse.ErrorOption.IsSet && logMessagesResponse.Error == null)
                throw new ArgumentNullException(nameof(logMessagesResponse.Error), "Property is required for class LogMessagesResponse.");

            if (logMessagesResponse.WatcherOption.IsSet && logMessagesResponse.Watcher == null)
                throw new ArgumentNullException(nameof(logMessagesResponse.Watcher), "Property is required for class LogMessagesResponse.");

            if (logMessagesResponse.HistoryOption.IsSet && logMessagesResponse.History == null)
                throw new ArgumentNullException(nameof(logMessagesResponse.History), "Property is required for class LogMessagesResponse.");

            if (logMessagesResponse.InfoOption.IsSet)
            {
                writer.WritePropertyName("info");
                JsonSerializer.Serialize(writer, logMessagesResponse.Info, jsonSerializerOptions);
            }
            if (logMessagesResponse.ResponseHeaderOption.IsSet)
            {
                writer.WritePropertyName("responseHeader");
                JsonSerializer.Serialize(writer, logMessagesResponse.ResponseHeader, jsonSerializerOptions);
            }
            if (logMessagesResponse.ErrorOption.IsSet)
            {
                writer.WritePropertyName("error");
                JsonSerializer.Serialize(writer, logMessagesResponse.Error, jsonSerializerOptions);
            }
            if (logMessagesResponse.WatcherOption.IsSet)
                writer.WriteString("watcher", logMessagesResponse.Watcher);

            if (logMessagesResponse.HistoryOption.IsSet)
            {
                writer.WritePropertyName("history");
                JsonSerializer.Serialize(writer, logMessagesResponse.History, jsonSerializerOptions);
            }
        }
    }
}
