// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RenameCoreRequestBody
    /// </summary>
    public partial class RenameCoreRequestBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RenameCoreRequestBody" /> class.
        /// </summary>
        /// <param name="to">The new name for the Solr core.</param>
        /// <param name="async">Request ID to track this action which will be processed asynchronously.</param>
        [JsonConstructor]
        public RenameCoreRequestBody(string to, Option<string?> async = default)
        {
            To = to;
            AsyncOption = async;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The new name for the Solr core.
        /// </summary>
        /// <value>The new name for the Solr core.</value>
        [JsonPropertyName("to")]
        public string To { get; set; }

        /// <summary>
        /// Used to track the state of Async
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AsyncOption { get; private set; }

        /// <summary>
        /// Request ID to track this action which will be processed asynchronously.
        /// </summary>
        /// <value>Request ID to track this action which will be processed asynchronously.</value>
        [JsonPropertyName("async")]
        public string? Async { get { return this.AsyncOption; } set { this.AsyncOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RenameCoreRequestBody {\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Async: ").Append(Async).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RenameCoreRequestBody" />
    /// </summary>
    public class RenameCoreRequestBodyJsonConverter : JsonConverter<RenameCoreRequestBody>
    {
        /// <summary>
        /// Deserializes json to <see cref="RenameCoreRequestBody" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RenameCoreRequestBody Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> to = default;
            Option<string?> async = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "to":
                            to = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "async":
                            async = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!to.IsSet)
                throw new ArgumentException("Property is required for class RenameCoreRequestBody.", nameof(to));

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class RenameCoreRequestBody.");

            if (async.IsSet && async.Value == null)
                throw new ArgumentNullException(nameof(async), "Property is not nullable for class RenameCoreRequestBody.");

            return new RenameCoreRequestBody(to.Value!, async);
        }

        /// <summary>
        /// Serializes a <see cref="RenameCoreRequestBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="renameCoreRequestBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RenameCoreRequestBody renameCoreRequestBody, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, renameCoreRequestBody, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RenameCoreRequestBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="renameCoreRequestBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RenameCoreRequestBody renameCoreRequestBody, JsonSerializerOptions jsonSerializerOptions)
        {
            if (renameCoreRequestBody.To == null)
                throw new ArgumentNullException(nameof(renameCoreRequestBody.To), "Property is required for class RenameCoreRequestBody.");

            if (renameCoreRequestBody.AsyncOption.IsSet && renameCoreRequestBody.Async == null)
                throw new ArgumentNullException(nameof(renameCoreRequestBody.Async), "Property is required for class RenameCoreRequestBody.");

            writer.WriteString("to", renameCoreRequestBody.To);

            if (renameCoreRequestBody.AsyncOption.IsSet)
                writer.WriteString("async", renameCoreRequestBody.Async);
        }
    }
}
