// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SchemaGetFieldInfoResponse
    /// </summary>
    public partial class SchemaGetFieldInfoResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaGetFieldInfoResponse" /> class.
        /// </summary>
        /// <param name="responseHeader">responseHeader</param>
        /// <param name="error">error</param>
        /// <param name="field">field</param>
        [JsonConstructor]
        public SchemaGetFieldInfoResponse(Option<ResponseHeader?> responseHeader = default, Option<ErrorInfo?> error = default, Option<Object?> field = default)
        {
            ResponseHeaderOption = responseHeader;
            ErrorOption = error;
            FieldOption = field;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ResponseHeader
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResponseHeader?> ResponseHeaderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResponseHeader
        /// </summary>
        [JsonPropertyName("responseHeader")]
        public ResponseHeader? ResponseHeader { get { return this.ResponseHeaderOption; } set { this.ResponseHeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ErrorInfo?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public ErrorInfo? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of Field
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> FieldOption { get; private set; }

        /// <summary>
        /// Gets or Sets Field
        /// </summary>
        [JsonPropertyName("field")]
        public Object? Field { get { return this.FieldOption; } set { this.FieldOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SchemaGetFieldInfoResponse {\n");
            sb.Append("  ResponseHeader: ").Append(ResponseHeader).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SchemaGetFieldInfoResponse" />
    /// </summary>
    public class SchemaGetFieldInfoResponseJsonConverter : JsonConverter<SchemaGetFieldInfoResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SchemaGetFieldInfoResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SchemaGetFieldInfoResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ResponseHeader?> responseHeader = default;
            Option<ErrorInfo?> error = default;
            Option<Object?> field = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "responseHeader":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                responseHeader = new Option<ResponseHeader?>(JsonSerializer.Deserialize<ResponseHeader>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                error = new Option<ErrorInfo?>(JsonSerializer.Deserialize<ErrorInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "field":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                field = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (responseHeader.IsSet && responseHeader.Value == null)
                throw new ArgumentNullException(nameof(responseHeader), "Property is not nullable for class SchemaGetFieldInfoResponse.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class SchemaGetFieldInfoResponse.");

            if (field.IsSet && field.Value == null)
                throw new ArgumentNullException(nameof(field), "Property is not nullable for class SchemaGetFieldInfoResponse.");

            return new SchemaGetFieldInfoResponse(responseHeader, error, field);
        }

        /// <summary>
        /// Serializes a <see cref="SchemaGetFieldInfoResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaGetFieldInfoResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SchemaGetFieldInfoResponse schemaGetFieldInfoResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, schemaGetFieldInfoResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SchemaGetFieldInfoResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaGetFieldInfoResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SchemaGetFieldInfoResponse schemaGetFieldInfoResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (schemaGetFieldInfoResponse.ResponseHeaderOption.IsSet && schemaGetFieldInfoResponse.ResponseHeader == null)
                throw new ArgumentNullException(nameof(schemaGetFieldInfoResponse.ResponseHeader), "Property is required for class SchemaGetFieldInfoResponse.");

            if (schemaGetFieldInfoResponse.ErrorOption.IsSet && schemaGetFieldInfoResponse.Error == null)
                throw new ArgumentNullException(nameof(schemaGetFieldInfoResponse.Error), "Property is required for class SchemaGetFieldInfoResponse.");

            if (schemaGetFieldInfoResponse.FieldOption.IsSet && schemaGetFieldInfoResponse.Field == null)
                throw new ArgumentNullException(nameof(schemaGetFieldInfoResponse.Field), "Property is required for class SchemaGetFieldInfoResponse.");

            if (schemaGetFieldInfoResponse.ResponseHeaderOption.IsSet)
            {
                writer.WritePropertyName("responseHeader");
                JsonSerializer.Serialize(writer, schemaGetFieldInfoResponse.ResponseHeader, jsonSerializerOptions);
            }
            if (schemaGetFieldInfoResponse.ErrorOption.IsSet)
            {
                writer.WritePropertyName("error");
                JsonSerializer.Serialize(writer, schemaGetFieldInfoResponse.Error, jsonSerializerOptions);
            }
            if (schemaGetFieldInfoResponse.FieldOption.IsSet)
            {
                writer.WritePropertyName("field");
                JsonSerializer.Serialize(writer, schemaGetFieldInfoResponse.Field, jsonSerializerOptions);
            }
        }
    }
}
