// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SchemaListFieldTypesResponse
    /// </summary>
    public partial class SchemaListFieldTypesResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchemaListFieldTypesResponse" /> class.
        /// </summary>
        /// <param name="responseHeader">responseHeader</param>
        /// <param name="error">error</param>
        /// <param name="fieldTypes">fieldTypes</param>
        [JsonConstructor]
        public SchemaListFieldTypesResponse(Option<ResponseHeader?> responseHeader = default, Option<ErrorInfo?> error = default, Option<List<Object>?> fieldTypes = default)
        {
            ResponseHeaderOption = responseHeader;
            ErrorOption = error;
            FieldTypesOption = fieldTypes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ResponseHeader
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResponseHeader?> ResponseHeaderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResponseHeader
        /// </summary>
        [JsonPropertyName("responseHeader")]
        public ResponseHeader? ResponseHeader { get { return this.ResponseHeaderOption; } set { this.ResponseHeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ErrorInfo?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public ErrorInfo? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of FieldTypes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>?> FieldTypesOption { get; private set; }

        /// <summary>
        /// Gets or Sets FieldTypes
        /// </summary>
        [JsonPropertyName("fieldTypes")]
        public List<Object>? FieldTypes { get { return this.FieldTypesOption; } set { this.FieldTypesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SchemaListFieldTypesResponse {\n");
            sb.Append("  ResponseHeader: ").Append(ResponseHeader).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  FieldTypes: ").Append(FieldTypes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SchemaListFieldTypesResponse" />
    /// </summary>
    public class SchemaListFieldTypesResponseJsonConverter : JsonConverter<SchemaListFieldTypesResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SchemaListFieldTypesResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SchemaListFieldTypesResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ResponseHeader?> responseHeader = default;
            Option<ErrorInfo?> error = default;
            Option<List<Object>?> fieldTypes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "responseHeader":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                responseHeader = new Option<ResponseHeader?>(JsonSerializer.Deserialize<ResponseHeader>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                error = new Option<ErrorInfo?>(JsonSerializer.Deserialize<ErrorInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fieldTypes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                fieldTypes = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (responseHeader.IsSet && responseHeader.Value == null)
                throw new ArgumentNullException(nameof(responseHeader), "Property is not nullable for class SchemaListFieldTypesResponse.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class SchemaListFieldTypesResponse.");

            if (fieldTypes.IsSet && fieldTypes.Value == null)
                throw new ArgumentNullException(nameof(fieldTypes), "Property is not nullable for class SchemaListFieldTypesResponse.");

            return new SchemaListFieldTypesResponse(responseHeader, error, fieldTypes);
        }

        /// <summary>
        /// Serializes a <see cref="SchemaListFieldTypesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaListFieldTypesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SchemaListFieldTypesResponse schemaListFieldTypesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, schemaListFieldTypesResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SchemaListFieldTypesResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="schemaListFieldTypesResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SchemaListFieldTypesResponse schemaListFieldTypesResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (schemaListFieldTypesResponse.ResponseHeaderOption.IsSet && schemaListFieldTypesResponse.ResponseHeader == null)
                throw new ArgumentNullException(nameof(schemaListFieldTypesResponse.ResponseHeader), "Property is required for class SchemaListFieldTypesResponse.");

            if (schemaListFieldTypesResponse.ErrorOption.IsSet && schemaListFieldTypesResponse.Error == null)
                throw new ArgumentNullException(nameof(schemaListFieldTypesResponse.Error), "Property is required for class SchemaListFieldTypesResponse.");

            if (schemaListFieldTypesResponse.FieldTypesOption.IsSet && schemaListFieldTypesResponse.FieldTypes == null)
                throw new ArgumentNullException(nameof(schemaListFieldTypesResponse.FieldTypes), "Property is required for class SchemaListFieldTypesResponse.");

            if (schemaListFieldTypesResponse.ResponseHeaderOption.IsSet)
            {
                writer.WritePropertyName("responseHeader");
                JsonSerializer.Serialize(writer, schemaListFieldTypesResponse.ResponseHeader, jsonSerializerOptions);
            }
            if (schemaListFieldTypesResponse.ErrorOption.IsSet)
            {
                writer.WritePropertyName("error");
                JsonSerializer.Serialize(writer, schemaListFieldTypesResponse.Error, jsonSerializerOptions);
            }
            if (schemaListFieldTypesResponse.FieldTypesOption.IsSet)
            {
                writer.WritePropertyName("fieldTypes");
                JsonSerializer.Serialize(writer, schemaListFieldTypesResponse.FieldTypes, jsonSerializerOptions);
            }
        }
    }
}
