// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// UnloadCoreRequestBody
    /// </summary>
    public partial class UnloadCoreRequestBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnloadCoreRequestBody" /> class.
        /// </summary>
        /// <param name="deleteIndex">If true, will remove the index when unloading the core.</param>
        /// <param name="deleteDataDir">If true, removes the data directory and all sub-directories.</param>
        /// <param name="deleteInstanceDir">If true, removes everything related to the core, including the index directory, configuration files and other related files.</param>
        /// <param name="async">Request ID to track this action which will be processed asynchronously.</param>
        [JsonConstructor]
        public UnloadCoreRequestBody(Option<bool?> deleteIndex = default, Option<bool?> deleteDataDir = default, Option<bool?> deleteInstanceDir = default, Option<string?> async = default)
        {
            DeleteIndexOption = deleteIndex;
            DeleteDataDirOption = deleteDataDir;
            DeleteInstanceDirOption = deleteInstanceDir;
            AsyncOption = async;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DeleteIndex
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DeleteIndexOption { get; private set; }

        /// <summary>
        /// If true, will remove the index when unloading the core.
        /// </summary>
        /// <value>If true, will remove the index when unloading the core.</value>
        [JsonPropertyName("deleteIndex")]
        public bool? DeleteIndex { get { return this.DeleteIndexOption; } set { this.DeleteIndexOption = new(value); } }

        /// <summary>
        /// Used to track the state of DeleteDataDir
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DeleteDataDirOption { get; private set; }

        /// <summary>
        /// If true, removes the data directory and all sub-directories.
        /// </summary>
        /// <value>If true, removes the data directory and all sub-directories.</value>
        [JsonPropertyName("deleteDataDir")]
        public bool? DeleteDataDir { get { return this.DeleteDataDirOption; } set { this.DeleteDataDirOption = new(value); } }

        /// <summary>
        /// Used to track the state of DeleteInstanceDir
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DeleteInstanceDirOption { get; private set; }

        /// <summary>
        /// If true, removes everything related to the core, including the index directory, configuration files and other related files.
        /// </summary>
        /// <value>If true, removes everything related to the core, including the index directory, configuration files and other related files.</value>
        [JsonPropertyName("deleteInstanceDir")]
        public bool? DeleteInstanceDir { get { return this.DeleteInstanceDirOption; } set { this.DeleteInstanceDirOption = new(value); } }

        /// <summary>
        /// Used to track the state of Async
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AsyncOption { get; private set; }

        /// <summary>
        /// Request ID to track this action which will be processed asynchronously.
        /// </summary>
        /// <value>Request ID to track this action which will be processed asynchronously.</value>
        [JsonPropertyName("async")]
        public string? Async { get { return this.AsyncOption; } set { this.AsyncOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UnloadCoreRequestBody {\n");
            sb.Append("  DeleteIndex: ").Append(DeleteIndex).Append("\n");
            sb.Append("  DeleteDataDir: ").Append(DeleteDataDir).Append("\n");
            sb.Append("  DeleteInstanceDir: ").Append(DeleteInstanceDir).Append("\n");
            sb.Append("  Async: ").Append(Async).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UnloadCoreRequestBody" />
    /// </summary>
    public class UnloadCoreRequestBodyJsonConverter : JsonConverter<UnloadCoreRequestBody>
    {
        /// <summary>
        /// Deserializes json to <see cref="UnloadCoreRequestBody" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UnloadCoreRequestBody Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> deleteIndex = default;
            Option<bool?> deleteDataDir = default;
            Option<bool?> deleteInstanceDir = default;
            Option<string?> async = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "deleteIndex":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                deleteIndex = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "deleteDataDir":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                deleteDataDir = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "deleteInstanceDir":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                deleteInstanceDir = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "async":
                            async = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (deleteIndex.IsSet && deleteIndex.Value == null)
                throw new ArgumentNullException(nameof(deleteIndex), "Property is not nullable for class UnloadCoreRequestBody.");

            if (deleteDataDir.IsSet && deleteDataDir.Value == null)
                throw new ArgumentNullException(nameof(deleteDataDir), "Property is not nullable for class UnloadCoreRequestBody.");

            if (deleteInstanceDir.IsSet && deleteInstanceDir.Value == null)
                throw new ArgumentNullException(nameof(deleteInstanceDir), "Property is not nullable for class UnloadCoreRequestBody.");

            if (async.IsSet && async.Value == null)
                throw new ArgumentNullException(nameof(async), "Property is not nullable for class UnloadCoreRequestBody.");

            return new UnloadCoreRequestBody(deleteIndex, deleteDataDir, deleteInstanceDir, async);
        }

        /// <summary>
        /// Serializes a <see cref="UnloadCoreRequestBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="unloadCoreRequestBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UnloadCoreRequestBody unloadCoreRequestBody, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, unloadCoreRequestBody, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UnloadCoreRequestBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="unloadCoreRequestBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UnloadCoreRequestBody unloadCoreRequestBody, JsonSerializerOptions jsonSerializerOptions)
        {
            if (unloadCoreRequestBody.AsyncOption.IsSet && unloadCoreRequestBody.Async == null)
                throw new ArgumentNullException(nameof(unloadCoreRequestBody.Async), "Property is required for class UnloadCoreRequestBody.");

            if (unloadCoreRequestBody.DeleteIndexOption.IsSet)
                writer.WriteBoolean("deleteIndex", unloadCoreRequestBody.DeleteIndexOption.Value!.Value);

            if (unloadCoreRequestBody.DeleteDataDirOption.IsSet)
                writer.WriteBoolean("deleteDataDir", unloadCoreRequestBody.DeleteDataDirOption.Value!.Value);

            if (unloadCoreRequestBody.DeleteInstanceDirOption.IsSet)
                writer.WriteBoolean("deleteInstanceDir", unloadCoreRequestBody.DeleteInstanceDirOption.Value!.Value);

            if (unloadCoreRequestBody.AsyncOption.IsSet)
                writer.WriteString("async", unloadCoreRequestBody.Async);
        }
    }
}
