// <auto-generated>
/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ZooKeeperListChildrenResponse
    /// </summary>
    public partial class ZooKeeperListChildrenResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZooKeeperListChildrenResponse" /> class.
        /// </summary>
        /// <param name="unknownFields">unknownFields</param>
        /// <param name="responseHeader">responseHeader</param>
        /// <param name="error">error</param>
        /// <param name="wARNING">wARNING</param>
        /// <param name="stat">stat</param>
        [JsonConstructor]
        public ZooKeeperListChildrenResponse(Option<Dictionary<string, Dictionary<string, ZooKeeperStat>>?> unknownFields = default, Option<ResponseHeader?> responseHeader = default, Option<ErrorInfo?> error = default, Option<string?> wARNING = default, Option<ZooKeeperStat?> stat = default)
        {
            UnknownFieldsOption = unknownFields;
            ResponseHeaderOption = responseHeader;
            ErrorOption = error;
            WARNINGOption = wARNING;
            StatOption = stat;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of UnknownFields
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Dictionary<string, ZooKeeperStat>>?> UnknownFieldsOption { get; private set; }

        /// <summary>
        /// Gets or Sets UnknownFields
        /// </summary>
        [JsonPropertyName("unknownFields")]
        public Dictionary<string, Dictionary<string, ZooKeeperStat>>? UnknownFields { get { return this.UnknownFieldsOption; } set { this.UnknownFieldsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ResponseHeader
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ResponseHeader?> ResponseHeaderOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResponseHeader
        /// </summary>
        [JsonPropertyName("responseHeader")]
        public ResponseHeader? ResponseHeader { get { return this.ResponseHeaderOption; } set { this.ResponseHeaderOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ErrorInfo?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public ErrorInfo? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Used to track the state of WARNING
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WARNINGOption { get; private set; }

        /// <summary>
        /// Gets or Sets WARNING
        /// </summary>
        [JsonPropertyName("WARNING")]
        public string? WARNING { get { return this.WARNINGOption; } set { this.WARNINGOption = new(value); } }

        /// <summary>
        /// Used to track the state of Stat
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ZooKeeperStat?> StatOption { get; private set; }

        /// <summary>
        /// Gets or Sets Stat
        /// </summary>
        [JsonPropertyName("stat")]
        public ZooKeeperStat? Stat { get { return this.StatOption; } set { this.StatOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZooKeeperListChildrenResponse {\n");
            sb.Append("  UnknownFields: ").Append(UnknownFields).Append("\n");
            sb.Append("  ResponseHeader: ").Append(ResponseHeader).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  WARNING: ").Append(WARNING).Append("\n");
            sb.Append("  Stat: ").Append(Stat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ZooKeeperListChildrenResponse" />
    /// </summary>
    public class ZooKeeperListChildrenResponseJsonConverter : JsonConverter<ZooKeeperListChildrenResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="ZooKeeperListChildrenResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ZooKeeperListChildrenResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, Dictionary<string, ZooKeeperStat>>?> unknownFields = default;
            Option<ResponseHeader?> responseHeader = default;
            Option<ErrorInfo?> error = default;
            Option<string?> wARNING = default;
            Option<ZooKeeperStat?> stat = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "unknownFields":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                unknownFields = new Option<Dictionary<string, Dictionary<string, ZooKeeperStat>>?>(JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, ZooKeeperStat>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "responseHeader":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                responseHeader = new Option<ResponseHeader?>(JsonSerializer.Deserialize<ResponseHeader>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "error":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                error = new Option<ErrorInfo?>(JsonSerializer.Deserialize<ErrorInfo>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "WARNING":
                            wARNING = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "stat":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                stat = new Option<ZooKeeperStat?>(JsonSerializer.Deserialize<ZooKeeperStat>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (unknownFields.IsSet && unknownFields.Value == null)
                throw new ArgumentNullException(nameof(unknownFields), "Property is not nullable for class ZooKeeperListChildrenResponse.");

            if (responseHeader.IsSet && responseHeader.Value == null)
                throw new ArgumentNullException(nameof(responseHeader), "Property is not nullable for class ZooKeeperListChildrenResponse.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class ZooKeeperListChildrenResponse.");

            if (wARNING.IsSet && wARNING.Value == null)
                throw new ArgumentNullException(nameof(wARNING), "Property is not nullable for class ZooKeeperListChildrenResponse.");

            if (stat.IsSet && stat.Value == null)
                throw new ArgumentNullException(nameof(stat), "Property is not nullable for class ZooKeeperListChildrenResponse.");

            return new ZooKeeperListChildrenResponse(unknownFields, responseHeader, error, wARNING, stat);
        }

        /// <summary>
        /// Serializes a <see cref="ZooKeeperListChildrenResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zooKeeperListChildrenResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ZooKeeperListChildrenResponse zooKeeperListChildrenResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, zooKeeperListChildrenResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ZooKeeperListChildrenResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zooKeeperListChildrenResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ZooKeeperListChildrenResponse zooKeeperListChildrenResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (zooKeeperListChildrenResponse.UnknownFieldsOption.IsSet && zooKeeperListChildrenResponse.UnknownFields == null)
                throw new ArgumentNullException(nameof(zooKeeperListChildrenResponse.UnknownFields), "Property is required for class ZooKeeperListChildrenResponse.");

            if (zooKeeperListChildrenResponse.ResponseHeaderOption.IsSet && zooKeeperListChildrenResponse.ResponseHeader == null)
                throw new ArgumentNullException(nameof(zooKeeperListChildrenResponse.ResponseHeader), "Property is required for class ZooKeeperListChildrenResponse.");

            if (zooKeeperListChildrenResponse.ErrorOption.IsSet && zooKeeperListChildrenResponse.Error == null)
                throw new ArgumentNullException(nameof(zooKeeperListChildrenResponse.Error), "Property is required for class ZooKeeperListChildrenResponse.");

            if (zooKeeperListChildrenResponse.WARNINGOption.IsSet && zooKeeperListChildrenResponse.WARNING == null)
                throw new ArgumentNullException(nameof(zooKeeperListChildrenResponse.WARNING), "Property is required for class ZooKeeperListChildrenResponse.");

            if (zooKeeperListChildrenResponse.StatOption.IsSet && zooKeeperListChildrenResponse.Stat == null)
                throw new ArgumentNullException(nameof(zooKeeperListChildrenResponse.Stat), "Property is required for class ZooKeeperListChildrenResponse.");

            if (zooKeeperListChildrenResponse.UnknownFieldsOption.IsSet)
            {
                writer.WritePropertyName("unknownFields");
                JsonSerializer.Serialize(writer, zooKeeperListChildrenResponse.UnknownFields, jsonSerializerOptions);
            }
            if (zooKeeperListChildrenResponse.ResponseHeaderOption.IsSet)
            {
                writer.WritePropertyName("responseHeader");
                JsonSerializer.Serialize(writer, zooKeeperListChildrenResponse.ResponseHeader, jsonSerializerOptions);
            }
            if (zooKeeperListChildrenResponse.ErrorOption.IsSet)
            {
                writer.WritePropertyName("error");
                JsonSerializer.Serialize(writer, zooKeeperListChildrenResponse.Error, jsonSerializerOptions);
            }
            if (zooKeeperListChildrenResponse.WARNINGOption.IsSet)
                writer.WriteString("WARNING", zooKeeperListChildrenResponse.WARNING);

            if (zooKeeperListChildrenResponse.StatOption.IsSet)
            {
                writer.WritePropertyName("stat");
                JsonSerializer.Serialize(writer, zooKeeperListChildrenResponse.Stat, jsonSerializerOptions);
            }
        }
    }
}
