/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using SolrClient.Client;
using SolrClient.Api;
// uncomment below to import models
//using SolrClient.Model;

namespace SolrClient.Test.Api
{
    /// <summary>
    ///  Class for testing ReplicaPropertiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReplicaPropertiesApiTests : IDisposable
    {
        private ReplicaPropertiesApi instance;

        public ReplicaPropertiesApiTests()
        {
            instance = new ReplicaPropertiesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplicaPropertiesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReplicaPropertiesApi
            //Assert.IsType<ReplicaPropertiesApi>(instance);
        }

        /// <summary>
        /// Test AddReplicaProperty
        /// </summary>
        [Fact]
        public void AddReplicaPropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collName = null;
            //string shardName = null;
            //string replicaName = null;
            //string propName = null;
            //AddReplicaPropertyRequestBodyModel addReplicaPropertyRequestBodyModel = null;
            //var response = instance.AddReplicaProperty(collName, shardName, replicaName, propName, addReplicaPropertyRequestBodyModel);
            //Assert.IsType<SolrJerseyResponseModel>(response);
        }

        /// <summary>
        /// Test DeleteReplicaProperty
        /// </summary>
        [Fact]
        public void DeleteReplicaPropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string collName = null;
            //string shardName = null;
            //string replicaName = null;
            //string propName = null;
            //var response = instance.DeleteReplicaProperty(collName, shardName, replicaName, propName);
            //Assert.IsType<SolrJerseyResponseModel>(response);
        }
    }
}
