/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BackupDeletionData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BackupDeletionDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BackupDeletionData
        //private BackupDeletionData instance;

        public BackupDeletionDataTests()
        {
            // TODO uncomment below to create an instance of BackupDeletionData
            //instance = new BackupDeletionData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BackupDeletionData
        /// </summary>
        [Fact]
        public void BackupDeletionDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" BackupDeletionData
            //Assert.IsType<BackupDeletionData>(instance);
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'BackupId'
        /// </summary>
        [Fact]
        public void BackupIdTest()
        {
            // TODO unit test for the property 'BackupId'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'NumFiles'
        /// </summary>
        [Fact]
        public void NumFilesTest()
        {
            // TODO unit test for the property 'NumFiles'
        }
    }
}
