/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CategoryRoutedAliasProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CategoryRoutedAliasPropertiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CategoryRoutedAliasProperties
        //private CategoryRoutedAliasProperties instance;

        public CategoryRoutedAliasPropertiesTests()
        {
            // TODO uncomment below to create an instance of CategoryRoutedAliasProperties
            //instance = new CategoryRoutedAliasProperties();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CategoryRoutedAliasProperties
        /// </summary>
        [Fact]
        public void CategoryRoutedAliasPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CategoryRoutedAliasProperties
            //Assert.IsType<CategoryRoutedAliasProperties>(instance);
        }

        /// <summary>
        /// Test the property 'MaxCardinality'
        /// </summary>
        [Fact]
        public void MaxCardinalityTest()
        {
            // TODO unit test for the property 'MaxCardinality'
        }

        /// <summary>
        /// Test the property 'MustMatch'
        /// </summary>
        [Fact]
        public void MustMatchTest()
        {
            // TODO unit test for the property 'MustMatch'
        }
    }
}
