/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCollectionRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCollectionRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCollectionRequestBody
        //private CreateCollectionRequestBody instance;

        public CreateCollectionRequestBodyTests()
        {
            // TODO uncomment below to create an instance of CreateCollectionRequestBody
            //instance = new CreateCollectionRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCollectionRequestBody
        /// </summary>
        [Fact]
        public void CreateCollectionRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCollectionRequestBody
            //Assert.IsType<CreateCollectionRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ReplicationFactor'
        /// </summary>
        [Fact]
        public void ReplicationFactorTest()
        {
            // TODO unit test for the property 'ReplicationFactor'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'NumShards'
        /// </summary>
        [Fact]
        public void NumShardsTest()
        {
            // TODO unit test for the property 'NumShards'
        }

        /// <summary>
        /// Test the property 'ShardNames'
        /// </summary>
        [Fact]
        public void ShardNamesTest()
        {
            // TODO unit test for the property 'ShardNames'
        }

        /// <summary>
        /// Test the property 'PullReplicas'
        /// </summary>
        [Fact]
        public void PullReplicasTest()
        {
            // TODO unit test for the property 'PullReplicas'
        }

        /// <summary>
        /// Test the property 'TlogReplicas'
        /// </summary>
        [Fact]
        public void TlogReplicasTest()
        {
            // TODO unit test for the property 'TlogReplicas'
        }

        /// <summary>
        /// Test the property 'NrtReplicas'
        /// </summary>
        [Fact]
        public void NrtReplicasTest()
        {
            // TODO unit test for the property 'NrtReplicas'
        }

        /// <summary>
        /// Test the property 'WaitForFinalState'
        /// </summary>
        [Fact]
        public void WaitForFinalStateTest()
        {
            // TODO unit test for the property 'WaitForFinalState'
        }

        /// <summary>
        /// Test the property 'PerReplicaState'
        /// </summary>
        [Fact]
        public void PerReplicaStateTest()
        {
            // TODO unit test for the property 'PerReplicaState'
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }

        /// <summary>
        /// Test the property 'Router'
        /// </summary>
        [Fact]
        public void RouterTest()
        {
            // TODO unit test for the property 'Router'
        }

        /// <summary>
        /// Test the property 'NodeSet'
        /// </summary>
        [Fact]
        public void NodeSetTest()
        {
            // TODO unit test for the property 'NodeSet'
        }

        /// <summary>
        /// Test the property 'CreateReplicas'
        /// </summary>
        [Fact]
        public void CreateReplicasTest()
        {
            // TODO unit test for the property 'CreateReplicas'
        }

        /// <summary>
        /// Test the property 'ShuffleNodes'
        /// </summary>
        [Fact]
        public void ShuffleNodesTest()
        {
            // TODO unit test for the property 'ShuffleNodes'
        }
    }
}
