/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FileListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FileListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FileListResponse
        //private FileListResponse instance;

        public FileListResponseTests()
        {
            // TODO uncomment below to create an instance of FileListResponse
            //instance = new FileListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FileListResponse
        /// </summary>
        [Fact]
        public void FileListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" FileListResponse
            //Assert.IsType<FileListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Filelist'
        /// </summary>
        [Fact]
        public void FilelistTest()
        {
            // TODO unit test for the property 'Filelist'
        }

        /// <summary>
        /// Test the property 'ConfFiles'
        /// </summary>
        [Fact]
        public void ConfFilesTest()
        {
            // TODO unit test for the property 'ConfFiles'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Exception'
        /// </summary>
        [Fact]
        public void ExceptionTest()
        {
            // TODO unit test for the property 'Exception'
        }
    }
}
