/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InstallShardDataRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstallShardDataRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstallShardDataRequestBody
        //private InstallShardDataRequestBody instance;

        public InstallShardDataRequestBodyTests()
        {
            // TODO uncomment below to create an instance of InstallShardDataRequestBody
            //instance = new InstallShardDataRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstallShardDataRequestBody
        /// </summary>
        [Fact]
        public void InstallShardDataRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstallShardDataRequestBody
            //Assert.IsType<InstallShardDataRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Repository'
        /// </summary>
        [Fact]
        public void RepositoryTest()
        {
            // TODO unit test for the property 'Repository'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
