/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ListLevelsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListLevelsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListLevelsResponse
        //private ListLevelsResponse instance;

        public ListLevelsResponseTests()
        {
            // TODO uncomment below to create an instance of ListLevelsResponse
            //instance = new ListLevelsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListLevelsResponse
        /// </summary>
        [Fact]
        public void ListLevelsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListLevelsResponse
            //Assert.IsType<ListLevelsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Levels'
        /// </summary>
        [Fact]
        public void LevelsTest()
        {
            // TODO unit test for the property 'Levels'
        }

        /// <summary>
        /// Test the property 'Loggers'
        /// </summary>
        [Fact]
        public void LoggersTest()
        {
            // TODO unit test for the property 'Loggers'
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Watcher'
        /// </summary>
        [Fact]
        public void WatcherTest()
        {
            // TODO unit test for the property 'Watcher'
        }
    }
}
