/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ListCoreSnapshotsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListCoreSnapshotsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListCoreSnapshotsResponse
        //private ListCoreSnapshotsResponse instance;

        public ListCoreSnapshotsResponseTests()
        {
            // TODO uncomment below to create an instance of ListCoreSnapshotsResponse
            //instance = new ListCoreSnapshotsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListCoreSnapshotsResponse
        /// </summary>
        [Fact]
        public void ListCoreSnapshotsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListCoreSnapshotsResponse
            //Assert.IsType<ListCoreSnapshotsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Snapshots'
        /// </summary>
        [Fact]
        public void SnapshotsTest()
        {
            // TODO unit test for the property 'Snapshots'
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
