/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PublicKeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicKeyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicKeyResponse
        //private PublicKeyResponse instance;

        public PublicKeyResponseTests()
        {
            // TODO uncomment below to create an instance of PublicKeyResponse
            //instance = new PublicKeyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicKeyResponse
        /// </summary>
        [Fact]
        public void PublicKeyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicKeyResponse
            //Assert.IsType<PublicKeyResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
    }
}
