/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SchemaVersionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchemaVersionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchemaVersionResponse
        //private SchemaVersionResponse instance;

        public SchemaVersionResponseTests()
        {
            // TODO uncomment below to create an instance of SchemaVersionResponse
            //instance = new SchemaVersionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchemaVersionResponse
        /// </summary>
        [Fact]
        public void SchemaVersionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchemaVersionResponse
            //Assert.IsType<SchemaVersionResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
