/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SchemaListDynamicFieldsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchemaListDynamicFieldsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SchemaListDynamicFieldsResponse
        //private SchemaListDynamicFieldsResponse instance;

        public SchemaListDynamicFieldsResponseTests()
        {
            // TODO uncomment below to create an instance of SchemaListDynamicFieldsResponse
            //instance = new SchemaListDynamicFieldsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SchemaListDynamicFieldsResponse
        /// </summary>
        [Fact]
        public void SchemaListDynamicFieldsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SchemaListDynamicFieldsResponse
            //Assert.IsType<SchemaListDynamicFieldsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ResponseHeader'
        /// </summary>
        [Fact]
        public void ResponseHeaderTest()
        {
            // TODO unit test for the property 'ResponseHeader'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'DynamicFields'
        /// </summary>
        [Fact]
        public void DynamicFieldsTest()
        {
            // TODO unit test for the property 'DynamicFields'
        }
    }
}
