/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SetThresholdRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetThresholdRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetThresholdRequestBody
        //private SetThresholdRequestBody instance;

        public SetThresholdRequestBodyTests()
        {
            // TODO uncomment below to create an instance of SetThresholdRequestBody
            //instance = new SetThresholdRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetThresholdRequestBody
        /// </summary>
        [Fact]
        public void SetThresholdRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetThresholdRequestBody
            //Assert.IsType<SetThresholdRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
    }
}
