/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAliasPropertiesRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAliasPropertiesRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAliasPropertiesRequestBody
        //private UpdateAliasPropertiesRequestBody instance;

        public UpdateAliasPropertiesRequestBodyTests()
        {
            // TODO uncomment below to create an instance of UpdateAliasPropertiesRequestBody
            //instance = new UpdateAliasPropertiesRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAliasPropertiesRequestBody
        /// </summary>
        [Fact]
        public void UpdateAliasPropertiesRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAliasPropertiesRequestBody
            //Assert.IsType<UpdateAliasPropertiesRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
