/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateAliasPropertyRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateAliasPropertyRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateAliasPropertyRequestBody
        //private UpdateAliasPropertyRequestBody instance;

        public UpdateAliasPropertyRequestBodyTests()
        {
            // TODO uncomment below to create an instance of UpdateAliasPropertyRequestBody
            //instance = new UpdateAliasPropertyRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateAliasPropertyRequestBody
        /// </summary>
        [Fact]
        public void UpdateAliasPropertyRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateAliasPropertyRequestBody
            //Assert.IsType<UpdateAliasPropertyRequestBody>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
