/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ApacheSolr.Model;
using ApacheSolr.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ApacheSolr.Test.Model
{
    /// <summary>
    ///  Class for testing CreateReplicaRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateReplicaRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateReplicaRequestBodyModel
        //private CreateReplicaRequestBodyModel instance;

        public CreateReplicaRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of CreateReplicaRequestBodyModel
            //instance = new CreateReplicaRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateReplicaRequestBodyModel
        /// </summary>
        [Fact]
        public void CreateReplicaRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateReplicaRequestBodyModel
            //Assert.IsType<CreateReplicaRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'InstanceDir'
        /// </summary>
        [Fact]
        public void InstanceDirTest()
        {
            // TODO unit test for the property 'InstanceDir'
        }

        /// <summary>
        /// Test the property 'DataDir'
        /// </summary>
        [Fact]
        public void DataDirTest()
        {
            // TODO unit test for the property 'DataDir'
        }

        /// <summary>
        /// Test the property 'UlogDir'
        /// </summary>
        [Fact]
        public void UlogDirTest()
        {
            // TODO unit test for the property 'UlogDir'
        }

        /// <summary>
        /// Test the property 'Route'
        /// </summary>
        [Fact]
        public void RouteTest()
        {
            // TODO unit test for the property 'Route'
        }

        /// <summary>
        /// Test the property 'NrtReplicas'
        /// </summary>
        [Fact]
        public void NrtReplicasTest()
        {
            // TODO unit test for the property 'NrtReplicas'
        }

        /// <summary>
        /// Test the property 'TlogReplicas'
        /// </summary>
        [Fact]
        public void TlogReplicasTest()
        {
            // TODO unit test for the property 'TlogReplicas'
        }

        /// <summary>
        /// Test the property 'PullReplicas'
        /// </summary>
        [Fact]
        public void PullReplicasTest()
        {
            // TODO unit test for the property 'PullReplicas'
        }

        /// <summary>
        /// Test the property 'WaitForFinalState'
        /// </summary>
        [Fact]
        public void WaitForFinalStateTest()
        {
            // TODO unit test for the property 'WaitForFinalState'
        }

        /// <summary>
        /// Test the property 'FollowAliases'
        /// </summary>
        [Fact]
        public void FollowAliasesTest()
        {
            // TODO unit test for the property 'FollowAliases'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }

        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }

        /// <summary>
        /// Test the property 'SkipNodeAssignment'
        /// </summary>
        [Fact]
        public void SkipNodeAssignmentTest()
        {
            // TODO unit test for the property 'SkipNodeAssignment'
        }

        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

        /// <summary>
        /// Test the property 'NodeSet'
        /// </summary>
        [Fact]
        public void NodeSetTest()
        {
            // TODO unit test for the property 'NodeSet'
        }
    }
}
