/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ApacheSolr.Model;
using ApacheSolr.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ApacheSolr.Test.Model
{
    /// <summary>
    ///  Class for testing RestoreCollectionRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestoreCollectionRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestoreCollectionRequestBodyModel
        //private RestoreCollectionRequestBodyModel instance;

        public RestoreCollectionRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of RestoreCollectionRequestBodyModel
            //instance = new RestoreCollectionRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestoreCollectionRequestBodyModel
        /// </summary>
        [Fact]
        public void RestoreCollectionRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestoreCollectionRequestBodyModel
            //Assert.IsType<RestoreCollectionRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'Collection'
        /// </summary>
        [Fact]
        public void CollectionTest()
        {
            // TODO unit test for the property 'Collection'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Repository'
        /// </summary>
        [Fact]
        public void RepositoryTest()
        {
            // TODO unit test for the property 'Repository'
        }

        /// <summary>
        /// Test the property 'BackupId'
        /// </summary>
        [Fact]
        public void BackupIdTest()
        {
            // TODO unit test for the property 'BackupId'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }

        /// <summary>
        /// Test the property 'CreateCollectionParams'
        /// </summary>
        [Fact]
        public void CreateCollectionParamsTest()
        {
            // TODO unit test for the property 'CreateCollectionParams'
        }
    }
}
