/*
 * v2 API
 *
 * OpenAPI spec for Solr's v2 API endpoints
 *
 * The version of the OpenAPI document: 9.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ApacheSolr.Model;
using ApacheSolr.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ApacheSolr.Test.Model
{
    /// <summary>
    ///  Class for testing UnloadCoreRequestBodyModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnloadCoreRequestBodyModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnloadCoreRequestBodyModel
        //private UnloadCoreRequestBodyModel instance;

        public UnloadCoreRequestBodyModelTests()
        {
            // TODO uncomment below to create an instance of UnloadCoreRequestBodyModel
            //instance = new UnloadCoreRequestBodyModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnloadCoreRequestBodyModel
        /// </summary>
        [Fact]
        public void UnloadCoreRequestBodyModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnloadCoreRequestBodyModel
            //Assert.IsType<UnloadCoreRequestBodyModel>(instance);
        }

        /// <summary>
        /// Test the property 'DeleteIndex'
        /// </summary>
        [Fact]
        public void DeleteIndexTest()
        {
            // TODO unit test for the property 'DeleteIndex'
        }

        /// <summary>
        /// Test the property 'DeleteDataDir'
        /// </summary>
        [Fact]
        public void DeleteDataDirTest()
        {
            // TODO unit test for the property 'DeleteDataDir'
        }

        /// <summary>
        /// Test the property 'DeleteInstanceDir'
        /// </summary>
        [Fact]
        public void DeleteInstanceDirTest()
        {
            // TODO unit test for the property 'DeleteInstanceDir'
        }

        /// <summary>
        /// Test the property 'Async'
        /// </summary>
        [Fact]
        public void AsyncTest()
        {
            // TODO unit test for the property 'Async'
        }
    }
}
